### ISSUE TITLE
Building the project fails

### ISSUE THREAD

**Issue by FieteO** [boldtrn/graphhopper-maps-capacitor#7]
I am trying to build the project. Initially I ran the `build.sh` and saw a couple of errors in the log output. So I took a look into the `build.sh` and ran the first commands until I got an error.
`npm install` runs fine but `npm run build` fails with two issues that may or may not be related to each other:
``` bash
fiete@ubu:~/Documents/development/graphhopper-maps-capacitor$ npm run build

> graphhopper-maps-capacitor@1.0.0 build
> webpack --config webpack.config.js

assets by status 14.1 KiB [cached] 3 assets
runtime modules 6.75 KiB 9 modules
orphan modules 401 bytes [orphan] 2 modules
cacheable modules 22.1 KiB
  ./src/app.js + 1 modules 2.14 KiB [built] [code generated]
  ./node_modules/@capacitor/core/dist/index.js 17 KiB [built] [code generated]
  ./node_modules/@capacitor-community/text-to-speech/dist/esm/web.js 3.03 KiB [built] [code generated]

ERROR in ./src/app.js 45:11-53
Module not found: Error: Can't resolve '../graphhopper-maps/dist/bundle' in '/home/fiete/Documents/development/graphhopper-maps-capacitor/src'
resolve '../graphhopper-maps/dist/bundle' in '/home/fiete/Documents/development/graphhopper-maps-capacitor/src'
  using description file: /home/fiete/Documents/development/graphhopper-maps-capacitor/package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /home/fiete/Documents/development/graphhopper-maps-capacitor/package.json (relative path: ./graphhopper-maps/dist/bundle)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /home/fiete/Documents/development/graphhopper-maps-capacitor/graphhopper-maps/dist/bundle doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /home/fiete/Documents/development/graphhopper-maps-capacitor/graphhopper-maps/dist/bundle.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /home/fiete/Documents/development/graphhopper-maps-capacitor/graphhopper-maps/dist/bundle.json doesn't exist
      .wasm
        Field 'browser' doesn't contain a valid alias configuration
        /home/fiete/Documents/development/graphhopper-maps-capacitor/graphhopper-maps/dist/bundle.wasm doesn't exist
      as directory
        /home/fiete/Documents/development/graphhopper-maps-capacitor/graphhopper-maps/dist/bundle doesn't exist

ERROR in   Error: Child compilation failed:
  Module not found: Error: Can't resolve '/home/fiete/Documents/development/graphhopper-maps-capacitor/graphhopper-maps/src/index.html' in '/home/fiete/Documents/development/graphhopper-maps-capacitor'
  ModuleNotFoundError: Module not found: Error: Can't resolve '/home/fiete/Documents/development/graphhopper-maps-capacitor/gra  phhopper-maps/src/index.html' in '/home/fiete/Documents/development/graphhopper-maps-capacitor'
      at /home/fiete/Documents/development/graphhopper-maps-capacitor/node_modules/webpack/lib/Compilation.js:2011:28
      at /home/fiete/Documents/development/graphhopper-maps-capacitor/node_modules/webpack/lib/NormalModuleFactory.js:795:13
      at eval (eval at create (/home/fiete/Documents/development/graphhopper-maps-capacitor/node_modules/tapable/lib/HookCodeFa  ctory.js:33:10), <anonymous>:10:1)
      at /home/fiete/Documents/development/graphhopper-maps-capacitor/node_modules/webpack/lib/NormalModuleFactory.js:275:22
      at eval (eval at create (/home/fiete/Documents/development/graphhopper-maps-capacitor/node_modules/tapable/lib/HookCodeFa  ctory.js:33:10), <anonymous>:9:1)
      at /home/fiete/Documents/development/graphhopper-maps-capacitor/node_modules/webpack/lib/NormalModuleFactory.js:431:22
      at /home/fiete/Documents/development/graphhopper-maps-capacitor/node_modules/webpack/lib/NormalModuleFactory.js:128:11
      at /home/fiete/Documents/development/graphhopper-maps-capacitor/node_modules/webpack/lib/NormalModuleFactory.js:667:25
      at /home/fiete/Documents/development/graphhopper-maps-capacitor/node_modules/webpack/lib/NormalModuleFactory.js:852:8
      at /home/fiete/Documents/development/graphhopper-maps-capacitor/node_modules/webpack/lib/NormalModuleFactory.js:972:5
  
  - Compilation.js:2011 
    [graphhopper-maps-capacitor]/[webpack]/lib/Compilation.js:2011:28
  
  - NormalModuleFactory.js:795 
    [graphhopper-maps-capacitor]/[webpack]/lib/NormalModuleFactory.js:795:13
  
  
  - NormalModuleFactory.js:275 
    [graphhopper-maps-capacitor]/[webpack]/lib/NormalModuleFactory.js:275:22
  
  
  - NormalModuleFactory.js:431 
    [graphhopper-maps-capacitor]/[webpack]/lib/NormalModuleFactory.js:431:22
  
  - NormalModuleFactory.js:128 
    [graphhopper-maps-capacitor]/[webpack]/lib/NormalModuleFactory.js:128:11
  
  - NormalModuleFactory.js:667 
    [graphhopper-maps-capacitor]/[webpack]/lib/NormalModuleFactory.js:667:25
  
  - NormalModuleFactory.js:852 
    [graphhopper-maps-capacitor]/[webpack]/lib/NormalModuleFactory.js:852:8
  
  - NormalModuleFactory.js:972 
    [graphhopper-maps-capacitor]/[webpack]/lib/NormalModuleFactory.js:972:5
  
  - child-compiler.js:169 
    [graphhopper-maps-capacitor]/[html-webpack-plugin]/lib/child-compiler.js:169:18
  
  - Compiler.js:559 
    [graphhopper-maps-capacitor]/[webpack]/lib/Compiler.js:559:11
  
  - Compiler.js:1129 
    [graphhopper-maps-capacitor]/[webpack]/lib/Compiler.js:1129:17
  
  
  - Hook.js:18 Hook.CALL_ASYNC_DELEGATE [as _callAsync]
    [graphhopper-maps-capacitor]/[tapable]/lib/Hook.js:18:14
  
  - Compiler.js:1125 
    [graphhopper-maps-capacitor]/[webpack]/lib/Compiler.js:1125:33
  
  - Compilation.js:2782 finalCallback
    [graphhopper-maps-capacitor]/[webpack]/lib/Compilation.js:2782:11
  
  - Compilation.js:3087 
    [graphhopper-maps-capacitor]/[webpack]/lib/Compilation.js:3087:11
  
  
  - Hook.js:18 Hook.CALL_ASYNC_DELEGATE [as _callAsync]
    [graphhopper-maps-capacitor]/[tapable]/lib/Hook.js:18:14
  


1 ERROR in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
webpack 5.65.0 compiled with 3 errors in 609 ms
```

There is the `Field 'browser' doesn't contain a valid alias configuration` error where I did not find an obvious solution for (maybe check [this SO thread](https://stackoverflow.com/questions/43037590/field-browser-doesnt-contain-a-valid-alias-configuration)) and a possible followup error that the `index.html` cannot be found.

**Comment by FieteO** [comment]
Okay, I get one step further now when changing the `entry` option in `webpack.config.js` to `entry: path.resolve(__dirname, 'src', 'app.js')`.
``` bash
fiete@ubu:~/Documents/development/graphhopper-maps-capacitor$ npm run build

> graphhopper-maps-capacitor@1.0.0 build
> webpack --config webpack.config.js

assets by status 10.7 KiB [cached] 3 assets
runtime modules 6.75 KiB 9 modules
orphan modules 401 bytes [orphan] 2 modules
cacheable modules 22.1 KiB
  ./src/app.js + 1 modules 2.14 KiB [built] [code generated]
  ./node_modules/@capacitor/core/dist/index.js 17 KiB [built] [code generated]
  ./node_modules/@capacitor-community/text-to-speech/dist/esm/web.js 3.03 KiB [built] [code generated]
  Entrypoint HtmlWebpackPlugin_0-0 =
  runtime modules 440 bytes 3 modules
  cacheable modules 363 bytes
    data:text/javascript,__webpack_public_path__ = __webpack_base_uri__ = htmlWebpackPluginPublicPath; 77 bytes [built] [code generated]
    ./node_modules/html-webpack-plugin/lib/loader.js!./graphhopper-maps/src/index.html 286 bytes [built] [code generated]
    
  Child HtmlWebpackCompiler compiled successfully

ERROR in ./src/app.js 45:11-53
Module not found: Error: Can't resolve '../graphhopper-maps/dist/bundle' in '/home/fiete/Documents/development/graphhopper-maps-capacitor/src'
resolve '../graphhopper-maps/dist/bundle' in '/home/fiete/Documents/development/graphhopper-maps-capacitor/src'
  using description file: /home/fiete/Documents/development/graphhopper-maps-capacitor/package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /home/fiete/Documents/development/graphhopper-maps-capacitor/package.json (relative path: ./graphhopper-maps/dist/bundle)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /home/fiete/Documents/development/graphhopper-maps-capacitor/graphhopper-maps/dist/bundle doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /home/fiete/Documents/development/graphhopper-maps-capacitor/graphhopper-maps/dist/bundle.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /home/fiete/Documents/development/graphhopper-maps-capacitor/graphhopper-maps/dist/bundle.json doesn't exist
      .wasm
        Field 'browser' doesn't contain a valid alias configuration
        /home/fiete/Documents/development/graphhopper-maps-capacitor/graphhopper-maps/dist/bundle.wasm doesn't exist
      as directory
        /home/fiete/Documents/development/graphhopper-maps-capacitor/graphhopper-maps/dist/bundle doesn't exist

webpack 5.65.0 compiled with 1 error in 537 ms
```
The error on line 45 in `app.js` is a require of `../graphhopper-maps/dist/bundle` which fails because the file does not exist:
``` bash
fiete@ubu:~/Documents/development/graphhopper-maps-capacitor$ tree graphhopper-maps/
graphhopper-maps/
├── config.js
└── src
    └── index.html

1 directory, 2 files
```

**Comment by FieteO** [comment]
After changing the output path in `webpack.config.js` to `__dirname, 'graphhopper-maps','dist'`, the `build.js` is correctly generated in `graphhopper-maps/dist`.
``` bash
    output: {
        path: path.resolve(__dirname, 'graphhopper-maps','dist'),
        filename: 'bundle.js',
    },
```

**Comment by FieteO** [comment]
To be honest I have never worked with capacitor before, so I have quite literally followed the README. Most likely I am missing something, here is my directory structure (I left out the deeper levels of everything but `dist`, `src` and `graphhopper-maps`):
``` bash
├── android
├── dist
│   ├── 452.bundle.js
│   ├── bundle.js
│   ├── bundle.js.LICENSE.txt
│   └── index.html
├── fastlane
├── graphhopper-maps
│   ├── config.js
│   ├── dist
│   │   ├── 452.bundle.js
│   │   ├── bundle.js
│   │   ├── bundle.js.LICENSE.txt
│   │   └── index.html
│   └── src
│       └── index.html
├── resources
├── src
│   └── app.js
├── build.sh
├── capacitor.config.json
├── config.js
├── LICENSE
├── output
├── output2
├── package.json
├── package-lock.json
├── README.md
└── webpack.config.js

875 directories, 25 files
```

**Comment by FieteO** [comment]
Okay, I have figured out the issue: A normal `git clone` does not fetch the `graphhopper-maps` submodule. I have created [a pull request](https://github.com/boldtrn/graphhopper-maps-capacitor/pull/8) to have this information in the README.
